<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>true</IsPackable>
        <PackageId>SCIRE.Foundation.Runtime</PackageId>
        <Version>0.1.0-alpha.1</Version>
        <Authors>net.cscience</Authors>
        <Description>Runtime components for SCIRE Foundation applications.</Description>

        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/net-cscience/scire-foundation</RepositoryUrl>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SCIRE.Foundation.Abstractions\SCIRE.Foundation.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    </ItemGroup>

</Project>